//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.ToDo.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samples.ToDo.API.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are empty.
        /// </summary>
        public static string Credentials_are_empty {
            get {
                return ResourceManager.GetString("Credentials_are_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are invalid.
        /// </summary>
        public static string Credentials_are_invalid {
            get {
                return ResourceManager.GetString("Credentials_are_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can&apos;t be empty.
        /// </summary>
        public static string Description_cant_be_empty {
            get {
                return ResourceManager.GetString("Description_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty.
        /// </summary>
        public static string Name_cant_be_empty {
            get {
                return ResourceManager.GetString("Name_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is not unique.
        /// </summary>
        public static string Name_is_not_unique {
            get {
                return ResourceManager.GetString("Name_is_not_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty.
        /// </summary>
        public static string Password_cant_be_empty {
            get {
                return ResourceManager.GetString("Password_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project id can&apos;t be empty.
        /// </summary>
        public static string Project_id_cant_be_empty {
            get {
                return ResourceManager.GetString("Project_id_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Id is invalid.
        /// </summary>
        public static string Project_id_is_invalid {
            get {
                return ResourceManager.GetString("Project_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status id can&apos;t be empty.
        /// </summary>
        public static string Status_id_cant_be_empty {
            get {
                return ResourceManager.GetString("Status_id_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status id is invalid.
        /// </summary>
        public static string Status_id_is_invalid {
            get {
                return ResourceManager.GetString("Status_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Id is invalid.
        /// </summary>
        public static string Tag_id_is_invalid {
            get {
                return ResourceManager.GetString("Tag_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags count can&apos;t be more than 5.
        /// </summary>
        public static string Tags_count_cant_be_more_than_5 {
            get {
                return ResourceManager.GetString("Tags_count_cant_be_more_than_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task id can&apos;t be empty.
        /// </summary>
        public static string Task_id_cant_be_empty {
            get {
                return ResourceManager.GetString("Task_id_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id is invalid.
        /// </summary>
        public static string Task_id_is_invalid {
            get {
                return ResourceManager.GetString("Task_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired.
        /// </summary>
        public static string Token_is_expired {
            get {
                return ResourceManager.GetString("Token_is_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid.
        /// </summary>
        public static string Token_is_invalid {
            get {
                return ResourceManager.GetString("Token_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id can&apos;t be empty.
        /// </summary>
        public static string User_id_cant_be_empty {
            get {
                return ResourceManager.GetString("User_id_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id is invalid.
        /// </summary>
        public static string User_id_is_invalid {
            get {
                return ResourceManager.GetString("User_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name can&apos;t be empty.
        /// </summary>
        public static string User_name_cant_be_empty {
            get {
                return ResourceManager.GetString("User_name_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is not unique.
        /// </summary>
        public static string User_name_is_not_unique {
            get {
                return ResourceManager.GetString("User_name_is_not_unique", resourceCulture);
            }
        }
    }
}
